#!/bin/bash
# WebSocket Fix - Quick Update Script for Apache
# Run this on your Apache proxy server

echo "WebSocket Fix - Apache Configuration Update"
echo "============================================"
echo ""
echo "This will update your Apache configuration to fix WebSocket connections."
echo ""
echo "WHAT TO DO:"
echo "1. Edit your Apache config file (usually /etc/apache2/sites-available/desktop.conf)"
echo "2. Find the ProxyPass line(s)"
echo "3. Add the 'upgrade=websocket' parameter"
echo ""
echo "CHANGE THIS:"
echo "  ProxyPass / http://172.22.0.27:5020/ retry=3 timeout=3600"
echo ""
echo "TO THIS:"
echo "  ProxyPass / http://172.22.0.27:5020/ upgrade=websocket retry=3 timeout=3600"
echo "                                         ^^^^^^^^^^^^^^^^^^"
echo "                                         Add this parameter"
echo ""
echo "4. Save the file"
echo "5. Run: sudo apache2ctl configtest"
echo "6. Run: sudo systemctl reload apache2"
echo ""
echo "REQUIREMENTS:"
echo "- Apache 2.4.47 or later"
echo "- mod_proxy_wstunnel enabled (sudo a2enmod proxy_wstunnel)"
echo ""
echo "That's it! The WebSocket connections should now work."
